import { generateResponse } from "@/lib/llm/server-providers"
import { prisma } from "@/lib/db"
import JSZip from "jszip"

export interface GeneratedProject {
  id: string
  title: string
  description: string
  framework: string
  files: Record<string, string>
  createdAt: Date
}

export const SUPPORTED_FRAMEWORKS = [
  { value: "nextjs", label: "Next.js", description: "Full-stack React framework" },
  { value: "react", label: "React", description: "React single-page application" },
  { value: "html", label: "HTML/CSS/JS", description: "Static HTML website" },
]

export async function generateCode(
  userId: string,
  prompt: string,
  framework = "nextjs",
  provider = "openai",
  model = "gpt-4",
): Promise<{ content: string; tokens: number }> {
  const systemPrompt = getSystemPrompt(framework)

  const messages = [
    { role: "system", content: systemPrompt },
    { role: "user", content: prompt },
  ]

  return await generateResponse(userId, provider, model, messages)
}

function getSystemPrompt(framework: string): string {
  const basePrompt = `You are an expert web developer. Generate complete, production-ready code based on the user's requirements.

IMPORTANT RULES:
1. Generate COMPLETE, WORKING code - no placeholders or TODOs
2. Include ALL necessary files for a functional application
3. Use modern best practices and clean code principles
4. Include proper error handling and loading states
5. Make the code responsive and accessible
6. Add comments explaining complex logic

OUTPUT FORMAT:
Structure your response as a JSON object with this exact format:
{
  "title": "Brief project title",
  "description": "Short description of what was built",
  "files": {
    "filename.ext": "file content here",
    "another-file.ext": "another file content"
  }
}

CRITICAL: Your entire response must be valid JSON. Do not include any text outside the JSON object.`

  switch (framework) {
    case "nextjs":
      return `${basePrompt}

NEXT.JS SPECIFIC REQUIREMENTS:
- Use Next.js 14 with App Router
- Include package.json with all dependencies
- Use TypeScript for all files
- Include proper layout.tsx and page.tsx files
- Use Tailwind CSS for styling
- Include proper error.tsx and loading.tsx files where needed
- Follow Next.js file structure conventions

Example file structure:
- package.json
- app/layout.tsx
- app/page.tsx
- app/globals.css
- components/ui/button.tsx (if needed)
- lib/utils.ts (if needed)`

    case "react":
      return `${basePrompt}

REACT SPECIFIC REQUIREMENTS:
- Use React 18 with functional components and hooks
- Include package.json with all dependencies
- Use TypeScript for all files
- Include proper index.html and main.tsx files
- Use Tailwind CSS for styling
- Include Vite configuration
- Follow React best practices

Example file structure:
- package.json
- index.html
- src/main.tsx
- src/App.tsx
- src/index.css
- src/components/Component.tsx (if needed)
- vite.config.ts`

    case "html":
      return `${basePrompt}

HTML SPECIFIC REQUIREMENTS:
- Use semantic HTML5
- Include modern CSS with Flexbox/Grid
- Use vanilla JavaScript (ES6+)
- Make it fully responsive
- Include proper meta tags
- Use external CDNs for any libraries if needed
- Follow web standards and accessibility guidelines

Example file structure:
- index.html
- styles.css
- script.js
- assets/image.jpg (if needed)`

    default:
      return basePrompt
  }
}

export async function parseGeneratedCode(response: string): Promise<{
  title: string
  description: string
  files: Record<string, string>
}> {
  try {
    // Try to extract JSON from the response
    const jsonMatch = response.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      throw new Error("No JSON found in response")
    }

    const parsed = JSON.parse(jsonMatch[0])

    if (!parsed.title || !parsed.description || !parsed.files) {
      throw new Error("Invalid response format")
    }

    return {
      title: parsed.title,
      description: parsed.description,
      files: parsed.files,
    }
  } catch (error) {
    console.error("Failed to parse generated code:", error)

    // Fallback: create a simple structure
    return {
      title: "Generated Project",
      description: "Code generated from prompt",
      files: {
        "README.md": "# Generated Project\n\nThis project was generated by Promptmetheus.\n\n" + response,
      },
    }
  }
}

export async function saveGeneratedCode(
  userId: string,
  title: string,
  description: string,
  framework: string,
  files: Record<string, string>,
): Promise<string> {
  const generatedCode = await prisma.generatedCode.create({
    data: {
      userId,
      title,
      description,
      framework,
      code: JSON.stringify(files),
    },
  })

  return generatedCode.id
}

export async function createZipFile(files: Record<string, string>): Promise<Buffer> {
  const zip = new JSZip()

  // Add all files to the zip
  Object.entries(files).forEach(([filename, content]) => {
    zip.file(filename, content)
  })

  // Generate the zip file
  return await zip.generateAsync({ type: "nodebuffer" })
}

export async function getGeneratedProjects(userId: string): Promise<GeneratedProject[]> {
  const projects = await prisma.generatedCode.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
  })

  return projects.map((project) => ({
    id: project.id,
    title: project.title,
    description: project.description || "",
    framework: project.framework,
    files: JSON.parse(project.code),
    createdAt: project.createdAt,
  }))
}
